comment: false

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - component_id: nuspec
      name: nuspec
      paths:
        - crates/nuspec/**
