name: Publish

on:
  push:
    tags: [ "v*" ]

env:
  CARGO_TERM_COLOR: always

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/checks.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  publish:
    needs: build
    strategy:
      matrix:
        crate: [ "nuspec" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2 # immutable action, safe to use the versions
      - uses: rust-lang/crates-io-auth-action@e919bc7605cde86df457cf5b93c5e103838bd879 # v1.0.1
        id: auth
      - name: Publish
        run: cargo publish --all-features --package ${{ matrix.crate }} --verbose
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
